source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Swift-test-Lib_Example', :exclusive => true do
  pod "Swift-test-Lib", :path => "../"
end

target 'Swift-test-Lib_Tests', :exclusive => true do
  pod "Swift-test-Lib", :path => "../"

  pod 'FBSnapshotTestCase'
end
